name: "Flinter.md"
description: "A customizable Markdown Frontmatter linter"
author: "JackDevAU"
branding:
  icon: "align-justify"
  color: "red"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  DEBUG:
    description: "Debug logging"
    required: false
    default: "false"

runs:
  using: "node16"
  main: "dist/index.js"
