const DEFAULT_VALID_MARKDOWN_EXTENSIONS = ['.md', '.mdx'];
const DEFAULT_VALID_IMAGE_EXTENSIONS = ['.svg', '.png', '.jpg', '.jpeg'];

export { DEFAULT_VALID_MARKDOWN_EXTENSIONS, DEFAULT_VALID_IMAGE_EXTENSIONS };
